= HP Chromebook 11 G1 =

The HP Chomebook 11 G1 is the first generation of 11.6 inch Chromebook laptops built by Hewlett-Packard, "Made with Google".

The laptop features:

include::section/common_specs.adoc[]
* 11.6", 1366x768 (16:9 ratio), 200 nits, IPS panel
* Two USB3 (Type-A) ports
* One microUSB port
** charger (up to 3A)
** HDMI via 5-pin Slimport

At the time of writing, the ChromeOS https://support.google.com/chrome/a/answer/6220366[Auto Update Expiry date] was
October 2018.

include::section/installation_options.adoc[]

include::section/hardware_support.adoc[]

include::section/first_time_setup.adoc[]

include::section/cross_compiler.adoc[]

include::section/building_a_kernel.adoc[]

include::section/boot_media.adoc[]

include::section/customisations.adoc[]

== Troubleshooting ==

=== Doesn't boot from USB ===

USB sticks can have different "modes" that enable feature detection.
The HP Chomebook 11 seems to have difficulty booting from some USB devices.

One way to check that the USB is not being booted is if the GPT attributes are
not being decremented. Set your partitions to Priority=15,Tries=15,Successful=0.
After every boot, Tries should decrease by one every time the laptop beeps.

Check `dmesg` when plugging in a USB stick into a Linux computer (or chromeOS's
`chrome://system` `dmesg`).

* Bootable USB: `Mode Sense: 23 00 00 00`
* Unbootable USB: `Mode Sense: 43 00 00 00`

=== Blank screen on boot ===

If you are building the chromiumOS kernel (3.8.11) source with gcc 6.4.0, when
booting the kernel the screen will stay lit but blank.

Build the kernel with gcc 5.4.0-r4.

=== Kernel modules won't load ===

If you are building a kernel with gcc 7.3.0-r3 and can't load modules
with `modprobe`, and `dmesg` mentions:

    Unknown symbol _GLOBAL_OFFSET_TABLE_ (err 0)

Build the kernel with gcc 5.4.0-r4.

A message regarding Chromium LSM module locking is probably a red herring,
but you can disable module locking with the kernel command line:

    lsm.module_locking=0

or by disabling the sysctl during runtime:

    # tee /proc/sys/kernel/chromium/module_locking <<<0

ifndef::wiki[]
link:index.html[]
endif::wiki[]
